name: Just chatting 💬 (Comments) 
description: General comments or other notes. Much appreciated!
title: "[Comment]: "
labels: ["comment"]
body:
  - type: markdown
    attributes:
      value: |
        Got comments to share? Let's hear them!
  - type: textarea
    id: what-happened
    attributes:
      label: What's up?
      description: Let me know what's on your mind.
      placeholder: Sup...
    validations:
      required: true
  - type: input
    id: relevant-link
    attributes:
      label: Relevant link
      description: If applicable, provide a link related to this issue.
      placeholder: https://example.com
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to share!