name: I got it! 🙋‍♀️ (Suggestions) 
description: You have an idea for an enhancement to the site. Lay them on me!
title: "[Suggestion]: "
labels: ["suggestion"]
body:
  - type: markdown
    attributes:
      value: |
        Got ideas to share? I'd love to hear them!
  - type: textarea
    id: what-happened
    attributes:
      label: What's your suggestion?
      description: What idea would you love to share?
      placeholder: What if...
    validations:
      required: true
  - type: input
    id: relevant-link
    attributes:
      label: Relevant link
      description: If applicable, provide a link related to this issue.
      placeholder: https://example.com
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to share your suggestions with me!